// SPDX-License-Identifier: MIT
// Copyright (c) 2026 hackernotfound — https://github.com/hackernotfound/dsh-tacit
/**
 * Builds the shipped browser bundle `client/client.js` from `client/src/`.
 *
 * The harness serves exactly one classic-script file per plugin, so the
 * sources are plain fragments of that one factory, concatenated in filename
 * order — no imports, no bundler, no transform. `--check` rebuilds in memory
 * and fails when the committed bundle differs from the sources.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const srcDir = path.join(root, 'client', 'src')
const outFile = path.join(root, 'client', 'client.js')
const BANNER = '// GENERATED by scripts/build-client.mjs from client/src/ — edit the sources, not this file.'

export async function buildClient() {
  const names = (await readdir(srcDir)).filter((name) => name.endsWith('.js')).sort()
  const parts = await Promise.all(names.map((name) => readFile(path.join(srcDir, name), 'utf8')))
  const lines = parts.join('').split('\n')
  // The banner goes right after the two-line license header of 00-header.js.
  lines.splice(2, 0, BANNER)
  return lines.join('\n')
}

const check = process.argv.includes('--check')
const built = await buildClient()
if (check) {
  const committed = await readFile(outFile, 'utf8').catch(() => '')
  if (committed !== built) {
    console.error('client/client.js is out of date — run `pnpm build:client` and commit the result.')
    process.exit(1)
  }
  console.log('client/client.js matches client/src/')
} else {
  await writeFile(outFile, built)
  console.log(`Built client/client.js from ${(await readdir(srcDir)).filter((n) => n.endsWith('.js')).length} source files`)
}
